/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a bluetooth_agent -c BluetoothAgentAdapter xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "bluetooth_agent.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class BluetoothAgentAdapter
 */

BluetoothAgentAdapter::BluetoothAgentAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

BluetoothAgentAdapter::~BluetoothAgentAdapter()
{
    // destructor
}

void BluetoothAgentAdapter::AuthorizeService(const QDBusObjectPath &in0, const QString &in1)
{
    // handle method call org.bluez.Agent1.AuthorizeService
    printf("1234\n");
    QMetaObject::invokeMethod(parent(), "AuthorizeService", Q_ARG(QDBusObjectPath, in0), Q_ARG(QString, in1));
}

void BluetoothAgentAdapter::Cancel()
{
    // handle method call org.bluez.Agent1.Cancel
    QMetaObject::invokeMethod(parent(), "Cancel");
}

void BluetoothAgentAdapter::DisplayPasskey(const QDBusObjectPath &in0, uint in1, ushort in2)
{
    // handle method call org.bluez.Agent1.DisplayPasskey
    QMetaObject::invokeMethod(parent(), "DisplayPasskey", Q_ARG(QDBusObjectPath, in0), Q_ARG(uint, in1), Q_ARG(ushort, in2));
}

void BluetoothAgentAdapter::DisplayPinCode(const QDBusObjectPath &in0, const QString &in1)
{
    // handle method call org.bluez.Agent1.DisplayPinCode
    QMetaObject::invokeMethod(parent(), "DisplayPinCode", Q_ARG(QDBusObjectPath, in0), Q_ARG(QString, in1));
}

void BluetoothAgentAdapter::Release()
{
    // handle method call org.bluez.Agent1.Release
    QMetaObject::invokeMethod(parent(), "Release");
}

void BluetoothAgentAdapter::RequestAuthorization(const QDBusObjectPath &in0)
{
    // handle method call org.bluez.Agent1.RequestAuthorization
    QMetaObject::invokeMethod(parent(), "RequestAuthorization", Q_ARG(QDBusObjectPath, in0));
}

void BluetoothAgentAdapter::RequestConfirmation(const QDBusObjectPath &in0, uint in1)
{
    // handle method call org.bluez.Agent1.RequestConfirmation
    QMetaObject::invokeMethod(parent(), "RequestConfirmation", Q_ARG(QDBusObjectPath, in0), Q_ARG(uint, in1));
}

uint BluetoothAgentAdapter::RequestPasskey(const QDBusObjectPath &in0)
{
    // handle method call org.bluez.Agent1.RequestPasskey
    uint out0;
    QMetaObject::invokeMethod(parent(), "RequestPasskey", Q_RETURN_ARG(uint, out0), Q_ARG(QDBusObjectPath, in0));
    return out0;
}

QString BluetoothAgentAdapter::RequestPinCode(const QDBusObjectPath &in0)
{
    // handle method call org.bluez.Agent1.RequestPinCode
    QString out0;
    QMetaObject::invokeMethod(parent(), "RequestPinCode", Q_RETURN_ARG(QString, out0), Q_ARG(QDBusObjectPath, in0));
    return out0;
}

